# Generated by Django 3.1.1 on 2020-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='connectors',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='topology',
            name='nodes',
            field=models.TextField(max_length=100000),
        ),
    ]
