# Generated by Django 3.1.1 on 2020-12-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interfaces',
        ),
    ]
