# Generated by Django 3.1.1 on 2020-10-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typesManage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
