# Generated by Django 3.1.1 on 2020-12-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20201221_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkequipment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.netconfusers'),
        ),
    ]
