# Generated by Django 3.1.1 on 2020-10-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nestatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nestatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NestatusType',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('show_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nestatus_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Networkequipment',
            fields=[
                ('neid', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('mac', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fixed_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('unittype', models.CharField(blank=True, db_column='unitType', max_length=255, null=True)),
                ('stock_date', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'networkequipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NeType',
            fields=[
                ('tid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ne_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetconfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('device_params', models.CharField(default='huawei', max_length=255)),
                ('hostkey', models.CharField(max_length=255, null=True)),
                ('equipment', models.ForeignKey(db_column='equipment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.networkequipment')),
            ],
            options={
                'db_table': 'netconfusers',
                'managed': True,
            },
        ),
    ]
