# Generated by Django 3.1.1 on 2020-10-31 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_param', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vendor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.vendor'),
        ),
    ]
