# Generated by Django 3.1.1 on 2020-10-31 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20201031_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.vendor'),
        ),
    ]
