# Generated by Django 3.1.1 on 2020-10-31 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_unittype_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkequipment',
            name='unittype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.unittype'),
        ),
    ]
