# Generated by Django 3.1.1 on 2020-10-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'function',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'params',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TempType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'temp_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('templateData', models.CharField(blank=True, max_length=1000, null=True)),
                ('updateDate', models.CharField(blank=True, max_length=100, null=True)),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configManage.function')),
                ('params', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configManage.params')),
                ('support', models.ManyToManyField(blank=True, null=True, to='equipment.UnitType')),
                ('tempType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configManage.temptype')),
            ],
            options={
                'db_table': 'templates',
                'managed': True,
            },
        ),
    ]
