# Generated by Django 3.1.1 on 2021-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
