# Generated by Django 3.1.1 on 2020-10-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configManage', '0002_auto_20201028_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='params',
        ),
        migrations.AddField(
            model_name='params',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configManage.templates'),
        ),
    ]
