# Generated by Django 3.1.1 on 2020-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configManage', '0003_auto_20201029_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='constraint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
