# Generated by Django 3.1.1 on 2021-02-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configManage', '0003_templates_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
