# Generated by Django 3.1.1 on 2020-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configManage', '0004_params_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
