# Generated by Django 3.1.1 on 2020-10-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('configManage', '0005_auto_20201029_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='support',
            field=models.ManyToManyField(to='equipment.UnitType'),
        ),
    ]
