# Generated by Django 3.1 on 2020-11-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configManage', '0006_auto_20201030_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='templateData',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
