# Generated by Django 3.1.1 on 2021-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configManage', '0002_params_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
